export declare const child_process: any;
export declare const path: any;
export declare const rootPath: any;
export declare const cwdPath: string;
export declare const packageJson: string;
export declare const currentTemplatePath: string;
export declare const cPackPath: string;
export declare const cTemplatePath: string;
export declare const supportCreateType: string[];
