"use strict";
exports.__esModule = true;
exports.cTemplateProjectPath = exports.cTemplatePath = exports.cPackPath = exports.currentTemplatePath = exports.packageJson = exports.cwdPath = exports.rootPath = exports.path = exports.child_process = void 0;
exports.child_process = require('child_process');
exports.path = require('path');
exports.rootPath = exports.path.resolve(exports.child_process.execSync('npm root').toString(), '../');
exports.cwdPath = process.cwd();
exports.packageJson = "".concat(exports.rootPath, "/package.json");
exports.currentTemplatePath = "".concat(exports.rootPath, "/template");
exports.cPackPath = "".concat(exports.rootPath, "/node_modules/capsules-pack");
exports.cTemplatePath = "".concat(exports.cPackPath, "/template");
exports.cTemplateProjectPath = "".concat(exports.cTemplatePath, "/project");
