"use strict";
exports.__esModule = true;
exports.cTemplatePath = exports.cPackPath = exports.currentTemplatePath = exports.packageJson = exports.cwdPath = exports.rootPath = exports.path = exports.child_process = void 0;
exports.child_process = require('child_process');
exports.path = require('path');
exports.rootPath = exports.path.resolve(__dirname.split('node_modules')[0]);
exports.cwdPath = process.cwd();
exports.packageJson = exports.path.resolve(exports.cwdPath, './package.json');
exports.currentTemplatePath = exports.path.resolve(exports.cwdPath, './template');
exports.cPackPath = exports.path.resolve(exports.rootPath, './node_modules/capsule-pack/lib');
exports.cTemplatePath = exports.path.resolve(exports.cPackPath, './tempalte');
